package com.github.MrMks.sapi.particle.animation;

import com.google.common.collect.ImmutableList;
import com.sucy.skill.dynamic.custom.EditorOption;

import java.util.List;

public class ParticleAnimationMaterial extends ParticleAnimationAbstract {

    private static final List<String> materials;
    private static final List<String> particles = ImmutableList.of("Block Crack", "Icon Crack");

    static {
        materials = ImmutableList.of(
                "Air",
                "Stone",
                "Grass",
                "Dirt",
                "Cobblestone",
                "Wood",
                "Sapling",
                "Bedrock",
                "Water",
                "Stationary Water",
                "Lava",
                "Stationary Lava",
                "Sand",
                "Gravel",
                "Gold Ore",
                "Iron Ore",
                "Coal Ore",
                "Log",
                "Leaves",
                "Sponge",
                "Glass",
                "Lapis Ore",
                "Lapis Block",
                "Dispenser",
                "Sandstone",
                "Note Block",
                "Bed Block",
                "Powered Rail",
                "Detector Rail",
                "Piston Sticky Base",
                "Web",
                "Long Grass",
                "Dead Bush",
                "Piston Base",
                "Piston Extension",
                "Wool",
                "Piston Moving Piece",
                "Yellow Flower",
                "Red Rose",
                "Brown Mushroom",
                "Red Mushroom",
                "Gold Block",
                "Iron Block",
                "Double Step",
                "Step",
                "Brick",
                "Tnt",
                "Bookshelf",
                "Mossy Cobblestone",
                "Obsidian",
                "Torch",
                "Fire",
                "Mob Spawner",
                "Wood Stairs",
                "Chest",
                "Redstone Wire",
                "Diamond Ore",
                "Diamond Block",
                "Workbench",
                "Crops",
                "Soil",
                "Furnace",
                "Burning Furnace",
                "Sign Post",
                "Wooden Door",
                "Ladder",
                "Rails",
                "Cobblestone Stairs",
                "Wall Sign",
                "Lever",
                "Stone Plate",
                "Iron Door Block",
                "Wood Plate",
                "Redstone Ore",
                "Glowing Redstone Ore",
                "Redstone Torch Off",
                "Redstone Torch On",
                "Stone Button",
                "Snow",
                "Ice",
                "Snow Block",
                "Cactus",
                "Clay",
                "Sugar Cane Block",
                "Jukebox",
                "Fence",
                "Pumpkin",
                "Netherrack",
                "Soul Sand",
                "Glowstone",
                "Portal",
                "Jack O Lantern",
                "Cake Block",
                "Diode Block Off",
                "Diode Block On",
                "Stained Glass",
                "Trap Door",
                "Monster Eggs",
                "Smooth Brick",
                "Huge Mushroom 1",
                "Huge Mushroom 2",
                "Iron Fence",
                "Thin Glass",
                "Melon Block",
                "Pumpkin Stem",
                "Melon Stem",
                "Vine",
                "Fence Gate",
                "Brick Stairs",
                "Smooth Stairs",
                "Mycel",
                "Water Lily",
                "Nether Brick",
                "Nether Fence",
                "Nether Brick Stairs",
                "Nether Warts",
                "Enchantment Table",
                "Brewing Stand",
                "Cauldron",
                "Ender Portal",
                "Ender Portal Frame",
                "Ender Stone",
                "Dragon Egg",
                "Redstone Lamp Off",
                "Redstone Lamp On",
                "Wood Double Step",
                "Wood Step",
                "Cocoa",
                "Sandstone Stairs",
                "Emerald Ore",
                "Ender Chest",
                "Tripwire Hook",
                "Tripwire",
                "Emerald Block",
                "Spruce Wood Stairs",
                "Birch Wood Stairs",
                "Jungle Wood Stairs",
                "Command",
                "Beacon",
                "Cobble Wall",
                "Flower Pot",
                "Carrot",
                "Potato",
                "Wood Button",
                "Skull",
                "Anvil",
                "Trapped Chest",
                "Gold Plate",
                "Iron Plate",
                "Redstone Comparator Off",
                "Redstone Comparator On",
                "Daylight Detector",
                "Redstone Block",
                "Quartz Ore",
                "Hopper",
                "Quartz Block",
                "Quartz Stairs",
                "Activator Rail",
                "Dropper",
                "Stained Clay",
                "Stained Glass Pane",
                "Leaves 2",
                "Log 2",
                "Acacia Stairs",
                "Dark Oak Stairs",
                "Slime Block",
                "Barrier",
                "Iron Trapdoor",
                "Prismarine",
                "Sea Lantern",
                "Hay Block",
                "Carpet",
                "Hard Clay",
                "Coal Block",
                "Packed Ice",
                "Double Plant",
                "Standing Banner",
                "Wall Banner",
                "Daylight Detector Inverted",
                "Red Sandstone",
                "Red Sandstone Stairs",
                "Double Stone Slab2",
                "Stone Slab2",
                "Spruce Fence Gate",
                "Birch Fence Gate",
                "Jungle Fence Gate",
                "Dark Oak Fence Gate",
                "Acacia Fence Gate",
                "Spruce Fence",
                "Birch Fence",
                "Jungle Fence",
                "Dark Oak Fence",
                "Acacia Fence",
                "Spruce Door",
                "Birch Door",
                "Jungle Door",
                "Acacia Door",
                "Dark Oak Door",
                "End Rod",
                "Chorus Plant",
                "Chorus Flower",
                "Purpur Block",
                "Purpur Pillar",
                "Purpur Stairs",
                "Purpur Double Slab",
                "Purpur Slab",
                "End Bricks",
                "Beetroot Block",
                "Grass Path",
                "End Gateway",
                "Command Repeating",
                "Command Chain",
                "Frosted Ice",
                "Magma",
                "Nether Wart Block",
                "Red Nether Brick",
                "Bone Block",
                "Structure Void",
                "Observer",
                "White Shulker Box",
                "Orange Shulker Box",
                "Magenta Shulker Box",
                "Light Blue Shulker Box",
                "Yellow Shulker Box",
                "Lime Shulker Box",
                "Pink Shulker Box",
                "Gray Shulker Box",
                "Silver Shulker Box",
                "Cyan Shulker Box",
                "Purple Shulker Box",
                "Blue Shulker Box",
                "Brown Shulker Box",
                "Green Shulker Box",
                "Red Shulker Box",
                "Black Shulker Box",
                "White Glazed Terracotta",
                "Orange Glazed Terracotta",
                "Magenta Glazed Terracotta",
                "Light Blue Glazed Terracotta",
                "Yellow Glazed Terracotta",
                "Lime Glazed Terracotta",
                "Pink Glazed Terracotta",
                "Gray Glazed Terracotta",
                "Silver Glazed Terracotta",
                "Cyan Glazed Terracotta",
                "Purple Glazed Terracotta",
                "Blue Glazed Terracotta",
                "Brown Glazed Terracotta",
                "Green Glazed Terracotta",
                "Red Glazed Terracotta",
                "Black Glazed Terracotta",
                "Concrete",
                "Concrete Powder",
                "Structure Block",
                "Iron Spade",
                "Iron Pickaxe",
                "Iron Axe",
                "Flint And Steel",
                "Apple",
                "Bow",
                "Arrow",
                "Coal",
                "Diamond",
                "Iron Ingot",
                "Gold Ingot",
                "Iron Sword",
                "Wood Sword",
                "Wood Spade",
                "Wood Pickaxe",
                "Wood Axe",
                "Stone Sword",
                "Stone Spade",
                "Stone Pickaxe",
                "Stone Axe",
                "Diamond Sword",
                "Diamond Spade",
                "Diamond Pickaxe",
                "Diamond Axe",
                "Stick",
                "Bowl",
                "Mushroom Soup",
                "Gold Sword",
                "Gold Spade",
                "Gold Pickaxe",
                "Gold Axe",
                "String",
                "Feather",
                "Sulphur",
                "Wood Hoe",
                "Stone Hoe",
                "Iron Hoe",
                "Diamond Hoe",
                "Gold Hoe",
                "Seeds",
                "Wheat",
                "Bread",
                "Leather Helmet",
                "Leather Chestplate",
                "Leather Leggings",
                "Leather Boots",
                "Chainmail Helmet",
                "Chainmail Chestplate",
                "Chainmail Leggings",
                "Chainmail Boots",
                "Iron Helmet",
                "Iron Chestplate",
                "Iron Leggings",
                "Iron Boots",
                "Diamond Helmet",
                "Diamond Chestplate",
                "Diamond Leggings",
                "Diamond Boots",
                "Gold Helmet",
                "Gold Chestplate",
                "Gold Leggings",
                "Gold Boots",
                "Flint",
                "Pork",
                "Grilled Pork",
                "Painting",
                "Golden Apple",
                "Sign",
                "Wood Door",
                "Bucket",
                "Water Bucket",
                "Lava Bucket",
                "Minecart",
                "Saddle",
                "Iron Door",
                "Redstone",
                "Snow Ball",
                "Boat",
                "Leather",
                "Milk Bucket",
                "Clay Brick",
                "Clay Ball",
                "Sugar Cane",
                "Paper",
                "Book",
                "Slime Ball",
                "Storage Minecart",
                "Powered Minecart",
                "Egg",
                "Compass",
                "Fishing Rod",
                "Watch",
                "Glowstone Dust",
                "Raw Fish",
                "Cooked Fish",
                "Ink Sack",
                "Bone",
                "Sugar",
                "Cake",
                "Bed",
                "Diode",
                "Cookie",
                "Map",
                "Shears",
                "Melon",
                "Pumpkin Seeds",
                "Melon Seeds",
                "Raw Beef",
                "Cooked Beef",
                "Raw Chicken",
                "Cooked Chicken",
                "Rotten Flesh",
                "Ender Pearl",
                "Blaze Rod",
                "Ghast Tear",
                "Gold Nugget",
                "Nether Stalk",
                "Potion",
                "Glass Bottle",
                "Spider Eye",
                "Fermented Spider Eye",
                "Blaze Powder",
                "Magma Cream",
                "Brewing Stand Item",
                "Cauldron Item",
                "Eye Of Ender",
                "Speckled Melon",
                "Monster Egg",
                "Exp Bottle",
                "Fireball",
                "Book And Quill",
                "Written Book",
                "Emerald",
                "Item Frame",
                "Flower Pot Item",
                "Carrot Item",
                "Potato Item",
                "Baked Potato",
                "Poisonous Potato",
                "Empty Map",
                "Golden Carrot",
                "Skull Item",
                "Carrot Stick",
                "Nether Star",
                "Pumpkin Pie",
                "Firework",
                "Firework Charge",
                "Enchanted Book",
                "Redstone Comparator",
                "Nether Brick Item",
                "Quartz",
                "Explosive Minecart",
                "Hopper Minecart",
                "Prismarine Shard",
                "Prismarine Crystals",
                "Rabbit",
                "Cooked Rabbit",
                "Rabbit Stew",
                "Rabbit Foot",
                "Rabbit Hide",
                "Armor Stand",
                "Iron Barding",
                "Gold Barding",
                "Diamond Barding",
                "Leash",
                "Name Tag",
                "Command Minecart",
                "Mutton",
                "Cooked Mutton",
                "Banner",
                "End Crystal",
                "Spruce Door Item",
                "Birch Door Item",
                "Jungle Door Item",
                "Acacia Door Item",
                "Dark Oak Door Item",
                "Chorus Fruit",
                "Chorus Fruit Popped",
                "Beetroot",
                "Beetroot Seeds",
                "Beetroot Soup",
                "Dragons Breath",
                "Splash Potion",
                "Spectral Arrow",
                "Tipped Arrow",
                "Lingering Potion",
                "Shield",
                "Elytra",
                "Boat Spruce",
                "Boat Birch",
                "Boat Jungle",
                "Boat Acacia",
                "Boat Dark Oak",
                "Totem",
                "Shulker Shell",
                "Iron Nugget",
                "Knowledge Book",
                "Gold Record",
                "Green Record",
                "Record 3",
                "Record 4",
                "Record 5",
                "Record 6",
                "Record 7",
                "Record 8",
                "Record 9",
                "Record 10",
                "Record 11",
                "Record 12"
        );
    }

    @Override
    protected List<String> getParticleOptions() {
        return particles;
    }

    @Override
    protected List<EditorOption> getExtraParticleOptions() {
        return ImmutableList.of(
                EditorOption.dropdown("material", "Material", "The material to use for the Block Crack or Icon Crack particles", materials),
                EditorOption.text("type", "Type", "The material data value to se for the Block Crack or Icon Crack particles", "0")
        );
    }

    @Override
    public String getKey() {
        return "Particle Anim M";
    }

    @Override
    public String getDescription() {
        return "";
    }

}
